#!/usr/bin/env bash
#
# Sets up a fresh Ubuntu droplet to run Blobgarden at https://anrpg.com.
# Run it once, as root, on a brand-new server:
#
#   curl -fsSL https://raw.githubusercontent.com/doublestoppd/bg/main/deploy/setup-droplet.sh | bash
#
# or copy the file over and run `bash setup-droplet.sh`. Afterwards the
# `blobgarden` command (see deploy/blobgarden) manages the server.
#
# What it installs:
#   * Node.js 22 (NodeSource), PostgreSQL (Ubuntu's package), Caddy (HTTPS).
#   * A `blobgarden` system user that owns /srv/blobgarden.
#   * The game, cloned from GitHub into /srv/blobgarden/app.
#   * /srv/blobgarden/.env with a random database password and session secret.
#   * A systemd service (blobgarden.service) that keeps the game running.
#   * Caddy, which obtains the certificate for the domain and proxies to the game.
#   * ufw, allowing only SSH, HTTP and HTTPS.
#
# It is safe to run again: everything it creates is skipped if present.
#
# Settings can be overridden by exporting them before running the script.
set -euo pipefail

DOMAIN="${DOMAIN:-anrpg.com}"
REPO_URL="${REPO_URL:-https://github.com/doublestoppd/bg.git}"
BRANCH="${BRANCH:-main}"
APP_PORT="${APP_PORT:-3000}"
NODE_MAJOR="${NODE_MAJOR:-22}"

SERVICE_USER=blobgarden
HOME_DIR=/srv/blobgarden
APP_DIR="$HOME_DIR/app"
ENV_FILE="$HOME_DIR/.env"
DB_USER=blobgarden
DB_NAME=blobgarden
TEST_DB_NAME=blobgarden_test

say() { printf '\n==> %s\n' "$*"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this script as root (for example: sudo bash setup-droplet.sh)." >&2
  exit 1
fi
if ! command -v apt-get >/dev/null; then
  echo "This script expects Ubuntu or Debian (it uses apt-get)." >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

say "Installing system packages"
# See the Caddy step: a broken third-party source from an earlier run would stop apt here.
rm -f /etc/apt/sources.list.d/caddy-stable.list
apt-get update -q
apt-get install -y -q ca-certificates curl git gnupg ufw postgresql

say "Installing Node.js $NODE_MAJOR"
if ! command -v node >/dev/null || [ "$(node -p 'process.versions.node.split(".")[0]')" -lt "$NODE_MAJOR" ]; then
  install -d -m 0755 /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
  apt-get update -q
  apt-get install -y -q nodejs
fi
node --version

say "Installing Caddy"
# Ubuntu ships Caddy in its own archive, which is all a reverse proxy with
# automatic HTTPS needs. Caddy's third-party apt repository (Cloudsmith)
# has refused downloads before, so an earlier attempt to add it is removed
# here or every later apt-get update would fail.
rm -f /etc/apt/sources.list.d/caddy-stable.list /etc/apt/keyrings/caddy-stable-archive-keyring.gpg
if ! command -v caddy >/dev/null; then
  apt-get update -q
  apt-get install -y -q caddy
fi
caddy version

say "Creating the $SERVICE_USER system user"
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --create-home --home-dir "$HOME_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$HOME_DIR"

say "Creating the PostgreSQL role and databases"
systemctl enable --now postgresql
if [ -f "$ENV_FILE" ]; then
  # Keep the password an earlier run generated so the existing role still matches.
  DB_PASSWORD="$(sed -n 's#^DATABASE_URL=postgres://[^:]*:\([^@]*\)@.*#\1#p' "$ENV_FILE")"
else
  DB_PASSWORD="$(openssl rand -hex 24)"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER'" | grep -q 1; then
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD'"
fi
for db in "$DB_NAME" "$TEST_DB_NAME"; do
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = '$db'" | grep -q 1; then
    sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE DATABASE $db OWNER $DB_USER"
  fi
done

say "Writing $ENV_FILE"
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<ENV
# Generated by deploy/setup-droplet.sh. The app reads this through app/.env.
NODE_ENV=production
PORT=$APP_PORT
# Caddy sits in front of the game, so trust one proxy hop.
TRUST_PROXY=1
DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME
TEST_DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$TEST_DB_NAME
SESSION_SECRET=$(openssl rand -hex 32)
ENV
  chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
fi

say "Downloading the game into $APP_DIR"
if [ ! -d "$APP_DIR/.git" ]; then
  sudo -u "$SERVICE_USER" -H git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
# The checkout owns nothing secret: the settings live one level up and are
# linked in, so a reset can delete and re-clone the app without losing them.
ln -sfn "$ENV_FILE" "$APP_DIR/.env"
chown -h "$SERVICE_USER:$SERVICE_USER" "$APP_DIR/.env"

say "Installing npm packages"
sudo -u "$SERVICE_USER" -H bash -c "cd '$APP_DIR' && npm install --omit=dev --no-audit --no-fund"

say "Installing the blobgarden management command"
install -m 0755 "$APP_DIR/deploy/blobgarden" /usr/local/bin/blobgarden

say "Installing the systemd service"
cat > /etc/systemd/system/blobgarden.service <<UNIT
[Unit]
Description=Blobgarden virtual pet game
After=network.target postgresql.service
Requires=postgresql.service

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/node --env-file=.env src/server.js
Restart=always
RestartSec=3
# The game only needs to write its own directory.
ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable --now blobgarden
systemctl restart blobgarden

say "Configuring Caddy for https://$DOMAIN"
cat > /etc/caddy/Caddyfile <<CADDY
# Generated by deploy/setup-droplet.sh. Caddy fetches and renews the
# certificate itself once the domain's DNS points at this server.
$DOMAIN, www.$DOMAIN {
	encode gzip
	reverse_proxy 127.0.0.1:$APP_PORT
}
CADDY
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
systemctl enable --now caddy
systemctl reload caddy

say "Opening the firewall for SSH, HTTP and HTTPS"
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null

say "Checking the game answers locally"
sleep 2
if curl -fsS -o /dev/null "http://127.0.0.1:$APP_PORT/"; then
  echo "The game is running."
else
  echo "The game did not answer on port $APP_PORT. See: journalctl -u blobgarden -n 50" >&2
  exit 1
fi

cat <<DONE

Blobgarden is set up.

  Site:      https://$DOMAIN  (works once the domain's A record points here)
  Code:      $APP_DIR
  Settings:  $ENV_FILE
  Logs:      blobgarden logs
  Update:    blobgarden update     (latest code, keeps players and pets)
  Reset:     blobgarden reset      (latest code and empty databases)
  Help:      blobgarden help
DONE
